version: 2
updates:

  # CommonJS (CJS)
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "04:00"
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - CJS
    versioning-strategy: increase
    target-branch: "commonjs"
    ignore:
      - dependency-name: "@types/node"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "mocha"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@caoer/peek-readable"
        versions: ["5.x"]
      - dependency-name: "token-types"
        versions: ["5.x"]

  # ECMAScript Module (ESM)
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "06:00"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    target-branch: "master"
    labels:
      - dependencies
      - ESM
    ignore:
      - dependency-name: "@caoer/peek-readable"
        versions: ["4.x"]
